[build]
builder = "DOCKERFILE"
dockerfilePath = "InclusingLenguage.API/Dockerfile"
watchPaths = ["InclusingLenguage.API/**"]

[deploy]
startCommand = ""
healthcheckPath = "/api/auth/config"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
